-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Enrollements"
(
    "enrollId" uuid NOT NULL,
    "topicId" uuid NOT NULL,
    "userId" uuid NOT NULL,
    joined_at timestamp without time zone,
    CONSTRAINT "Enrollements_pkey" PRIMARY KEY ("enrollId")
);

CREATE TABLE IF NOT EXISTS public."Questions"
(
    "qId" uuid NOT NULL,
    "testId" uuid NOT NULL,
    question text COLLATE pg_catalog."default" NOT NULL,
    options json NOT NULL,
    answer text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT "Questions_pkey" PRIMARY KEY ("qId")
);

CREATE TABLE IF NOT EXISTS public."Test"
(
    "testId" uuid NOT NULL,
    "topicId" uuid,
    "userId" uuid,
    name text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    "startTime" timestamp without time zone,
    "endTime" timestamp without time zone,
    created_at timestamp without time zone,
    CONSTRAINT "Test_pkey" PRIMARY KEY ("testId")
);

CREATE TABLE IF NOT EXISTS public."Topics"
(
    "topicId" uuid NOT NULL,
    "userId" uuid NOT NULL,
    "topicName" text COLLATE pg_catalog."default" NOT NULL,
    "isPublic" boolean NOT NULL DEFAULT true,
    "topicCode" text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT "Topics_pkey" PRIMARY KEY ("topicId")
);

CREATE TABLE IF NOT EXISTS public."User"
(
    "userId" uuid NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    username text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    CONSTRAINT "User_pkey" PRIMARY KEY ("userId")
);

CREATE TABLE IF NOT EXISTS public."UserAnswers"
(
    "attemptId" uuid NOT NULL,
    "qId" uuid NOT NULL,
    answer text COLLATE pg_catalog."default" NOT NULL,
    "userAnsId" uuid NOT NULL,
    CONSTRAINT "UserAnswers_pkey" PRIMARY KEY ("userAnsId")
);

CREATE TABLE IF NOT EXISTS public."UserAttempts"
(
    "attemptId" uuid NOT NULL,
    "testId" uuid NOT NULL,
    "userId" uuid NOT NULL,
    started_at timestamp without time zone NOT NULL,
    completed_at timestamp without time zone NOT NULL,
    score bigint NOT NULL,
    CONSTRAINT "UserAttempts_pkey" PRIMARY KEY ("attemptId")
);

ALTER TABLE IF EXISTS public."Enrollements"
    ADD CONSTRAINT "topicId" FOREIGN KEY ("topicId")
    REFERENCES public."Topics" ("topicId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Enrollements"
    ADD CONSTRAINT "userId" FOREIGN KEY ("userId")
    REFERENCES public."User" ("userId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Questions"
    ADD CONSTRAINT "testId" FOREIGN KEY ("testId")
    REFERENCES public."Test" ("testId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Test"
    ADD CONSTRAINT "topicId" FOREIGN KEY ("topicId")
    REFERENCES public."Topics" ("topicId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Test"
    ADD CONSTRAINT "userId" FOREIGN KEY ("userId")
    REFERENCES public."User" ("userId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Topics"
    ADD CONSTRAINT "userId" FOREIGN KEY ("userId")
    REFERENCES public."User" ("userId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."UserAnswers"
    ADD CONSTRAINT "attemptId" FOREIGN KEY ("attemptId")
    REFERENCES public."UserAttempts" ("attemptId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."UserAnswers"
    ADD CONSTRAINT "qId" FOREIGN KEY ("qId")
    REFERENCES public."Questions" ("qId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."UserAttempts"
    ADD CONSTRAINT "testId" FOREIGN KEY ("testId")
    REFERENCES public."Test" ("testId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."UserAttempts"
    ADD CONSTRAINT "userId" FOREIGN KEY ("userId")
    REFERENCES public."User" ("userId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;